services:
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: ztl
      MYSQL_PASSWORD: ztl
      MYSQL_ROOT_PASSWORD: ztl2
      MYSQL_DATABASE: scheddy
    volumes:
      - ztl-scheddy-data:/var/lib/mysql
volumes:
  ztl-scheddy-data: